openapi: 3.0.1
info:
  version: '1.0.0'
  title: 'Find My Tutor Dashboard API'
  description: 'API providing basic functionalities of the Find My Tutor '
  termsOfService: https://foo.com/terms-of-use
  contact:
    name: Tri Huynh
    url: https://wwwmatthes.in.tum.de/pages/v4xzukutru9w/Tri-Huynh
    email: tri.huynh@tum.de
  license:
    name: MIT License
    url: https://opensource.org/licenses/MIT

tags:
  - name: user
    description: Access to sign up or log in
  - name: tutor
    description: Access to add or upload tutor's profile
  - name: customer
    description: Access to add or upload customer's profile
  - name: contact
    description: Access to contact the customer service team
  - name: tutorial
    description: Access to do CRU operation on a tutorial session object or get all tutorial sessions with a list of ids.


paths:
  /user/register:
    summary: For user registration
    description: Each each is identified by an unique email
    post:
      tags:
        - user
      requestBody:
        description: user object that needs to be added to the database
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/registerForms'
        required: true
      responses:
        200:
          $ref: '#/components/httpCodesSchemas/200'
        400:
          $ref: '#/components/httpCodesSchemas/400'
        500:
          $ref: '#/components/httpCodesSchemas/500'


  /user/login:
    summary: For user login.
    description: Only valid user can use this backend service
    post:
      tags:
        - user
      requestBody:
        description: user object that needs to be verified
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/loginForms'
        required: true
      responses:
        200:
          description: token created
        400:
          $ref: '#/components/httpCodesSchemas/400'
        404:
          $ref: '#/components/httpCodesSchemas/404'
        500:
          $ref: '#/components/httpCodesSchemas/500'

  /user/createTutorial:
    summary: To create a new tutorial.
    description: Only valid user can use this backend service
    put:
      tags:
        - tutorial
      parameters:
        - name: x-access-token
          in: header
          description: JWT token
          required: true
          schema:
            type: string
            format: byte
      requestBody:
        description: user object that needs to be verified
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/tutorialForms'
        required: true
      responses:
        200:
          $ref: '#/components/schemas/tutorialForms'
        400:
          $ref: '#/components/httpCodesSchemas/400'
        404:
          $ref: '#/components/httpCodesSchemas/404'
        500:
          $ref: '#/components/httpCodesSchemas/500'
  /tutor/confirmTutorial:
    summary: To confirm a tutorial.
    description: Only valid user can use this backend service
    post:
      tags:
        - tutorial
      parameters:
        - name: x-access-token
          in: header
          description: JWT token
          required: true
          schema:
            type: string
            format: byte
      requestBody:
        description: user object that needs to be verified
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/confirmTutorialForms'
        required: true
      responses:
        200:
          description: token created
        400:
          $ref: '#/components/httpCodesSchemas/400'
        404:
          $ref: '#/components/httpCodesSchemas/404'
        500:
          $ref: '#/components/httpCodesSchemas/500'
  /user/cancelTutorial:
    summary: To cancel a tutorial.
    description: Only valid user can use this backend service
    post:
      tags:
        - tutorial
      parameters:
        - name: x-access-token
          in: header
          description: JWT token
          required: true
          schema:
            type: string
            format: byte
      requestBody:
        description: user object that needs to be verified
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/cancelTutorialForms'
        required: true
      responses:
        200:
          description: token created
        400:
          $ref: '#/components/httpCodesSchemas/400'
        404:
          $ref: '#/components/httpCodesSchemas/404'
        500:
          $ref: '#/components/httpCodesSchemas/500'
  /user/getAllTutorials:
    summary: To get the detail of a list of tutorials.
    description: Only valid user can use this backend service
    post:
      tags:
        - tutorial
      parameters:
        - name: x-access-token
          in: header
          description: JWT token
          required: true
          schema:
            type: string
            format: byte
      requestBody:
        description: a list of tutorial ids
        content:
          application/json:
            schema:
              type: array
              items:
                - type: string
        required: true
      responses:
        200:
          description: token created
        400:
          $ref: '#/components/httpCodesSchemas/400'
        404:
          $ref: '#/components/httpCodesSchemas/404'
        500:
          $ref: '#/components/httpCodesSchemas/500'
  /user/closeTutorial:
    summary: For close a tutorial.
    description: Only valid user can use this backend service
    post:
      tags:
      - tutorial
      parameters:
      - name: x-access-token
        in: header
        description: JWT token
        required: true
        schema:
          type: string
          format: byte
      requestBody:
        description: user object that needs to be verified
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/closeTutorialForms'
        required: true
      responses:
        200:
          description: token created
        400:
          $ref: '#/components/httpCodesSchemas/400'
        404:
          $ref: '#/components/httpCodesSchemas/404'
        500:
          $ref: '#/components/httpCodesSchemas/500'

  /tutor/uploadTutorProfile:
    summary: For tutor upload Tutor Profile.
    description: Only valid tutor can use this backend service
    post:
      tags:
        - tutor
      parameters:
        - name: x-access-token
          in: header
          description: JWT token
          required: true
          schema:
            type: string
            format: byte
      requestBody:
        description: user object that needs to be verified
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/tutorProfileForms'
        required: true
      responses:
        200:
          description: Successfully update
        400:
          $ref: '#/components/httpCodesSchemas/400'
        404:
          $ref: '#/components/httpCodesSchemas/404'
        500:
          $ref: '#/components/httpCodesSchemas/500'
  /tutor/tutorProfile:
    summary: to ger Tutor Profile.
    description: Only valid tutor can use this backend service
    get:
      tags:
        - tutor
      parameters:
        - name: x-access-token
          in: header
          description: JWT token
          required: true
          schema:
            type: string
            format: byte
      responses:
        200:
          description: Load tutor profile
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/tutorProfileForms'
        400:
          $ref: '#/components/httpCodesSchemas/400'
        404:
          $ref: '#/components/httpCodesSchemas/404'
        500:
          $ref: '#/components/httpCodesSchemas/500'

  /customer/uploadCustomerProfile:
    summary: For Customer upload Customer Profile.
    description: Only valid Customer can use this backend service
    post:
      tags:
        - customer
      parameters:
        - name: x-access-token
          in: header
          description: JWT token
          required: true
          schema:
            type: string
            format: byte
      requestBody:
        description: customer profile to update
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/customerProfileForms'
        required: true
      responses:
        200:
          description: Successfully updated
        400:
          $ref: '#/components/httpCodesSchemas/400'
        404:
          $ref: '#/components/httpCodesSchemas/404'
        500:
          $ref: '#/components/httpCodesSchemas/500'
  
  /customer/customerProfile:
    summary: To get Customer Profile.
    description: Only valid Customer can use this backend service
    get:
      tags:
        - customer
      parameters:
        - name: x-access-token
          in: header
          description: JWT token
          required: true
          schema:
            type: string
            format: byte
      responses:
        200:
          description: Customer profile loaded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/customerProfileForms'
        400:
          $ref: '#/components/httpCodesSchemas/400'
        404:
          $ref: '#/components/httpCodesSchemas/404'
        500:
          $ref: '#/components/httpCodesSchemas/500'

  /contact/saveMessage:
    summary: save a contact message
    description: This endpoint is used to store the contact message sent by our customers/tutors. Each contactMessage is identified by an unique message_id.
    post:
      tags:
        - contact
      summary: Add a new message into the database
      operationId: postMessage
      requestBody:
        description: Message object that needs to be added to the database
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/contactForms'
        required: true
      responses:
        201:
          $ref: '#/components/httpCodesSchemas/200'
        401:
          $ref: '#/components/httpCodesSchemas/401'
        500:
          $ref: '#/components/httpCodesSchemas/500'



components:
  schemas:
    registerForms:
      type: object
      $ref: '#/components/schemas/registerForms'
      properties:
        email:
          type: string
        password: # length must greater than 8
          type: string
        userType:
          type: string
    loginForms:
      type: object
      $ref: '#/components/schemas/loginForms'
      properties:
        email:
          type: string
        password: # length must greater than 8
          type: string
        userType:
          type: string
    contactForms:
      type: object
      $ref: '#/components/schemas/contactForms'
      properties:
        firstName:
          type: string
        email:
          type: string
        message:
          type: string
    tutorialForms:
      type: object
      $ref: '#/components/schemas/tutorialForms'
      properties:
        tutorFirstName:
          type: string
        userType:
          type: string
        tutorEmail:
          type: string
        customerEmail:
          type: string
        sessionTopic:
          type: string
        bookedTime:
          type: string
        price:
          type: string
    confirmTutorialForms:
      type: object
      $ref: '#/components/schemas/confirmTutorialForms'
      properties:
        _id:
          type: string
        status:
          type: string
        tutorFirstName:
          type: string
        customerEmail:
          type: string
    closeTutorialForms:
      type: object
      $ref: '#/components/schemas/closeTutorialForms'
      properties:
        _id:
          type: string
        status:
          type: string
    cancelTutorialForms:
      type: object
      $ref: '#/components/schemas/cancelTutorialForms'
      properties:
        tutorFirstName:
          type: string
        _id:
          type: string
        tutorEmail:
          type: string
        customerEmail:
          type: string
        customerFirstName:
          type: string
        status:
          type: string
    tutorProfileForms:
      type: object
      $ref: '#/components/schemas/tutorProfileForms'
      properties:
        email:
          type: string
        firstName: 
          type: string
        lastName: 
          type: string
        university:
          type: string
        price:
          type: string
        description:
          type: string
    customerProfileForms:
      type: object
      $ref: '#/components/schemas/customerProfileForms'
      properties:
        email:
          type: string
        firstName: 
          type: string
        lastName: 
          type: string
        university:
          type: string
        

  securitySchemas:
    authenticationHeader:
      type: apiKey
      $ref: '#/components/securitySchemas/authenticationHeader'
      in: header
      name: Authentication
      description: Enter your authentication identity

  httpCodesSchemas:
    200:
      $ref: '#/components/httpCodesSchemas/200'
      description: Successful operation
    201:
      $ref: '#/components/httpCodesSchemas/201'
      description: New resource created
    400:
      $ref: '#/components/httpCodesSchemas/400'
      description: Invalid request
      content: {}
    401:
      $ref: '#/components/httpCodesSchemas/401'
      description: Unauthorized
    404:
      $ref: '#/components/httpCodesSchemas/404'
      description: data object is not found
      content: {}
    405:
      $ref: '#/components/httpCodesSchemas/405'
      description: Validation exception
      content: {}
    500:
      $ref: '#/components/httpCodesSchemas/500'
      description: internal error happened by mongodb database